version: '3.7'

services:
  fe_support:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fe_support
    image: dedisalam/fe_support
    ports:
      - '80:80'
      - '443:443'
    restart: 'unless-stopped'
    networks:
      - backend

networks:
  backend:
    name: backend
