version: '3.7'

services:
  fe_support:
    container_name: fe_support
    image: dedisalam/fe_support
    ports:
      - '80:80'
      - '443:443'
    restart: 'unless-stopped'
    networks:
      - production

networks:
  production:
    name: production
